# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0003_auto_20170803_1427'),
        ('employers', '0007_auto_20170807_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('role_type', models.CharField(choices=[('F', 'Full Time'), ('P', 'Part Time')], max_length=20)),
                ('about', models.TextField()),
                ('working_hours', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('0', 'Created'), ('1', 'Matches Found'), ('2', 'In Conversations'), ('3', 'Matched')], max_length=20)),
                ('salary', models.FloatField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.Company')),
            ],
        ),
        migrations.CreateModel(
            name='PostingEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employers.Employee')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postings.Posting')),
            ],
        ),
        migrations.CreateModel(
            name='PostingInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.Interest')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postings.Posting')),
            ],
        ),
        migrations.CreateModel(
            name='PostingLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.Location')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postings.Posting')),
            ],
        ),
        migrations.CreateModel(
            name='PostingSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postings.Posting')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='posting',
            name='employees',
            field=models.ManyToManyField(blank=True, through='postings.PostingEmployee', to='employers.Employee'),
        ),
        migrations.AddField(
            model_name='posting',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.Employer'),
        ),
        migrations.AddField(
            model_name='posting',
            name='interests',
            field=models.ManyToManyField(blank=True, through='postings.PostingInterest', to='commons.Interest'),
        ),
        migrations.AddField(
            model_name='posting',
            name='locations',
            field=models.ManyToManyField(blank=True, through='postings.PostingLocation', to='commons.Location'),
        ),
        migrations.AddField(
            model_name='posting',
            name='skills',
            field=models.ManyToManyField(blank=True, through='postings.PostingSkill', to='commons.Skill'),
        ),
        migrations.AddField(
            model_name='posting',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employers.Team'),
        ),
    ]
