# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingPsychometrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extroversion', models.IntegerField()),
                ('neuroticism', models.IntegerField()),
                ('openness_to_experience', models.IntegerField()),
                ('conscientiousness', models.IntegerField()),
                ('agreeableness', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='posting',
            name='psychometrics',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='postings.PostingPsychometrics'),
            preserve_default=False,
        ),
    ]
