# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_auto_20170809_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='psychometrics',
        ),
        migrations.AddField(
            model_name='postingpsychometrics',
            name='posting',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='postings.Posting'),
            preserve_default=False,
        ),
    ]
