# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0003_auto_20170803_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('short_bio', models.CharField(max_length=140)),
                ('long_bio', models.TextField()),
                ('size', models.CharField(choices=[('0', '1-5'), ('1', '6-10'), ('2', '11-20'), ('3', '21-50'), ('4', '51-100'), ('5', '100+')], max_length=20)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.Company')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.Industry')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('job_title', models.CharField(max_length=255)),
                ('is_lead', models.BooleanField(default=False)),
                ('employed_by_company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='employers.Company')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employers.Employer')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.Interest')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerPsychometrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extroversion', models.IntegerField()),
                ('neuroticism', models.IntegerField()),
                ('openness_to_experience', models.IntegerField()),
                ('conscientiousness', models.IntegerField()),
                ('agreeableness', models.IntegerField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.Company')),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='interests',
            field=models.ManyToManyField(blank=True, through='employers.EmployerInterest', to='commons.Interest'),
        ),
        migrations.AddField(
            model_name='employer',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='employers.Team'),
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='company_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.Employer'),
        ),
        migrations.AddField(
            model_name='company',
            name='industries',
            field=models.ManyToManyField(blank=True, through='employers.CompanyIndustry', to='commons.Industry'),
        ),
    ]
