# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0003_auto_20170803_1427'),
        ('employers', '0003_remove_employer_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('job_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.Employee')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.Interest')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePsychometrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extroversion', models.IntegerField()),
                ('neuroticism', models.IntegerField()),
                ('openness_to_experience', models.IntegerField()),
                ('conscientiousness', models.IntegerField()),
                ('agreeableness', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.Employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employers.Team')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='interests',
            field=models.ManyToManyField(blank=True, through='employers.EmployeeInterest', to='commons.Interest'),
        ),
        migrations.AddField(
            model_name='employee',
            name='teams',
            field=models.ManyToManyField(blank=True, through='employers.TeamMember', to='employers.Team'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
