# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_auto_20170807_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employers.Company'),
            preserve_default=False,
        ),
    ]
