# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0006_auto_20170807_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepsychometrics',
            name='agreeableness',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employeepsychometrics',
            name='conscientiousness',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employeepsychometrics',
            name='extroversion',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employeepsychometrics',
            name='neuroticism',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employeepsychometrics',
            name='openness_to_experience',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
