# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='category',
            field=models.CharField(blank=True, choices=[('AERO', 'Aerospace Industry'), ('AGRI', 'Agriculture'), ('CHEM', 'Chemical Industry'), ('COMP', 'Computer Industry'), ('CONS', 'Construction'), ('DEFE', 'Defense Industry'), ('EDUC', 'Education'), ('ENER', 'Energy Industry'), ('ENTE', 'Entertainment Industry'), ('FINA', 'Financial Services'), ('FOOD', 'Food Industry'), ('HEAL', 'Healthcare Industry'), ('HOSP', 'Hospitality Industry'), ('INFO', 'Infomation Industry'), ('MANU', 'Manufacturing Industry'), ('MASS', 'Mass Media'), ('TELE', 'Telecommunications Industry'), ('TRAN', 'Transport Industry'), ('WATE', 'Water Industry')], max_length=100),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
