# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('about', models.TextField(blank=True)),
                ('birth_date', models.DateField(null=True)),
                ('right_to_work', models.NullBooleanField()),
                ('linkedin_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Candidate')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.Location')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatePsychometrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extroversion', models.IntegerField()),
                ('neuroticism', models.IntegerField()),
                ('openness_to_experience', models.IntegerField()),
                ('conscientiousness', models.IntegerField()),
                ('agreeableness', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='locations',
            field=models.ManyToManyField(blank=True, through='accounts.CandidateLocation', to='commons.Location'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(blank=True, through='accounts.CandidateSkill', to='commons.Skill'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
