# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_interest'),
        ('accounts', '0002_auto_20170705_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.BigIntegerField(default=8771645002022988732, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidateskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.Skill'),
        ),
        migrations.AddField(
            model_name='candidateinterest',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Candidate'),
        ),
        migrations.AddField(
            model_name='candidateinterest',
            name='interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.Interest'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interests',
            field=models.ManyToManyField(blank=True, through='accounts.CandidateInterest', to='commons.Interest'),
        ),
    ]
