# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170801_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCandidate', models.BooleanField(default=False)),
                ('isEmployer', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.BigIntegerField(default=7852495803623741159, editable=False, primary_key=True, serialize=False),
        ),
    ]
