# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170803_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.BigIntegerField(default=7410620385226399127, editable=False, primary_key=True, serialize=False),
        ),
    ]
