# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170803_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.BigIntegerField(default=7608971043999658216, editable=False, primary_key=True, serialize=False),
        ),
    ]
