# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170805_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.BigIntegerField(default=6659079946015284, editable=False, primary_key=True, serialize=False),
        ),
    ]
