# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170806_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.BigIntegerField(default=3615433471142839, editable=False, primary_key=True, serialize=False),
        ),
    ]
