# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170806_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepsychometrics',
            name='strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.BigIntegerField(default=8267675791363472, editable=False, primary_key=True, serialize=False),
        ),
    ]
