# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170807_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.BigIntegerField(default=1837706421325294, editable=False, primary_key=True, serialize=False),
        ),
    ]
