# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170813_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.BigIntegerField(default=1516594819418157, editable=False, primary_key=True, serialize=False),
        ),
    ]
