# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 15:29
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170814_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.BigIntegerField(default=accounts.models.generate_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
