# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postings', '0003_auto_20170810_1740'),
        ('accounts', '0011_auto_20170813_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psycho_score', models.FloatField()),
                ('psycho_type', models.CharField(max_length=50)),
                ('skill_score', models.FloatField()),
                ('interest_score', models.FloatField()),
                ('location_score', models.FloatField()),
                ('total_match_score', models.FloatField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Candidate')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postings.Posting')),
            ],
        ),
    ]
